### ISSUE TITLE
want optional NAMESERVER env variable for dig

### ISSUE THREAD

**Issue by sreboot** [arekinath/triton-dehydrated#36]
In some cases direct DNS out to the Internet is not allowed. PR https://github.com/joyent/triton-dehydrated/pull/33 adds an optional NAMESERVER variable.

As a side note, the NAMESERVER DNS server should have a rule to send Letsencrypt validation requests directly up to 8.8.8.8. This is required for consistency between internal and external DNS validation lookups. Internal validation lookup must match external Letsencrypt ones.

**Comment by bahamat** [comment]
Fixed in #33
